version: '3.8'

services:

  mysql-db:
    container_name: mysql-db
    image: mysql:8.0.20
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      MYSQL_ROOT_USER: $DB_USERNAME
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql-db:/docker-entrypoint-initdb.d/
    networks:
      - default

  nestjs-app:
    container_name: nestjs-app
    depends_on:
      - mysql-db
    build: ./nestjs-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
      - OMDB_APIKEY=$OMDB_APIKEY
      - OMDB_URL=$OMDB_URL
    volumes:
      - ./nestjs-app:/app
      - /app/node_modules
    networks:
      - default

volumes:
  mysql-volume:


networks:
  default:
