import { MovieReview } from './movie-review';

export const dummyMovieReviews: MovieReview[] = [
    {
        id: '1',
        title: 'Epic Adventure',
        notes: 'A breathtaking journey with stunning visuals.',
        genre: 'Adventure, Fantasy',
        year: '2019',
        directors: ['Alex Rivera'],
        actors: ['Emma Watson', 'Daniel Radcliffe'],
        runtime: '142 min',
        rated: 'PG',
        ratings: [
            'Internet Movie Database: 8.2/10',
            'Rotten Tomatoes: 92%',
            'Metacritic: 88/100',
        ],
        metascore: '88',
        imdbRating: '8.2',
        imdbVotes: '500,000',
        country: 'United Kingdom',
        released: '2019-12-15',
    },
    {
        id: '2',
        title: 'Sci-Fi Thriller',
        notes: 'An edge-of-your-seat experience that redefines the genre.',
        genre: 'Sci-Fi, Thriller',
        year: '2021',
        directors: ['Jordan Peele'],
        actors: ["Lupita Nyong'o", 'Winston Duke'],
        runtime: '115 min',
        rated: 'R',
        ratings: [
            'Internet Movie Database: 7.9/10',
            'Rotten Tomatoes: 85%',
            'Metacritic: 75/100',
        ],
        metascore: '75',
        imdbRating: '7.9',
        imdbVotes: '350,000',
        country: 'United States',
        released: '2021-07-09',
    },
    {
        id: '3',
        title: 'Romantic Comedy',
        notes: 'A heartwarming tale that delivers laughter and love in equal measure.',
        genre: 'Comedy, Romance',
        year: '2018',
        directors: ['Nora Ephron'],
        actors: ['Meg Ryan', 'Tom Hanks'],
        runtime: '119 min',
        rated: 'PG-13',
        ratings: [
            'Internet Movie Database: 6.8/10',
            'Rotten Tomatoes: 78%',
            'Metacritic: 67/100',
        ],
        metascore: '67',
        imdbRating: '6.8',
        imdbVotes: '200,000',
        country: 'United States',
        released: '2018-02-14',
    },
    {
        id: '4',
        title: 'Historical Drama',
        notes: 'A poignant exploration of history that resonates with contemporary themes.',
        genre: 'Drama, History',
        year: '2017',
        directors: ['Steven Spielberg'],
        actors: ['Meryl Streep', 'Tom Hanks'],
        runtime: '116 min',
        rated: 'PG-13',
        ratings: [
            'Internet Movie Database: 7.2/10',
            'Rotten Tomatoes: 88%',
            'Metacritic: 83/100',
        ],
        metascore: '83',
        imdbRating: '7.2',
        imdbVotes: '150,000',
        country: 'United States',
        released: '2017-12-22',
    },
];
